import React,{useState} from "react";
import {api} from "../lib/api";
const SYSTEM_INSTRUCTION=`You are AI Code Studio, an autonomous coding assistant. You have real tools to inspect and modify the user's workspace and run commands. Do not merely describe how to do a task: perform it with tools. Never invent file contents. Read files before editing them. Preserve existing architecture and make the smallest necessary changes. For a new project, create required files from scratch. Run appropriate checks. Ask before destructive actions. Respond in the user's language/register.`;
export default function ChatPanel({modelId,autoMode,workspace,onEvents,onWorkspaceChange}){
 const [messages,setMessages]=useState([]),[input,setInput]=useState(""),[loading,setLoading]=useState(false);
 const send=async()=>{if(!input.trim()||loading)return; const task=input.trim(),next=[...messages,{role:"user",content:task}];setMessages(next);setInput("");setLoading(true);
 try{let useModel=modelId;if(autoMode){const p=await api.autoPickModel({needsDeepReasoning:task.length>400,isQuickEdit:task.length<80,inputTokensEstimate:task.length/4});useModel=p.model}
 let assistantText="";await api.agentChat({workspace,modelId:useModel,messages:next,systemInstruction:SYSTEM_INSTRUCTION,onEvent:e=>{onEvents?.(e);if(e.type==="assistant_delta")assistantText+=e.text||"";if(["file_change","done"].includes(e.type))onWorkspaceChange?.();}});
 setMessages(m=>[...m,{role:"assistant",content:assistantText||"(Task completed — live activity mein details dekhein.)"}]);
 }catch(err){onEvents?.({type:"error",error:err.message});setMessages(m=>[...m,{role:"assistant",content:`⚠️ Error: ${err.message}`}]);}finally{setLoading(false)}};
 return <div className="chat-panel"><div className="chat-messages">{messages.map((m,i)=><div key={i} className={`chat-msg ${m.role}`}>{m.content}</div>)}{loading&&<div className="chat-msg assistant">Working… live activity mein progress dikh rahi hai.</div>}</div><div className="chat-input-row"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Task batayein... Enter = send, Shift+Enter = new line"/><button onClick={send} disabled={loading}>{loading?"…":"Send"}</button></div></div>
}